//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddressBook.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Dear {0},
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Your account has been created by admin.
        ///	&lt;br/&gt;
        ///	UserId: {1}
        ///	&lt;br/&gt;
        ///	Password: {2}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Please confirm your email by clicking the following link.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    {3}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Yours sincerely,
        ///    &lt;br/&gt;
        ///    Address Book.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string AccountCreationTemplate {
            get {
                return ResourceManager.GetString("AccountCreationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Dear {0},
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Please confirm your email by clicking the following link.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    {1}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Yours sincerely,
        ///    &lt;br/&gt;
        ///    Address Book.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string ConfirmEmailTemplate {
            get {
                return ResourceManager.GetString("ConfirmEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Dear {0},
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Your temporary password is {1}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Please click the following link to reset your password.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    {2}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Yours sincerely,
        ///    &lt;br/&gt;
        ///    Address Book.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string ResetPasswordTemplate {
            get {
                return ResourceManager.GetString("ResetPasswordTemplate", resourceCulture);
            }
        }
    }
}
